[package]
name = "rust-sudoku-solver"
version = "0.1.5"
authors = ["Seb Nilsson <seb.nilsson@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
